name: Call snyk-workflow-master

on: workflow_dispatch

jobs:
  collect-snyk-filter-master:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout .snyk file from private repo
        uses: actions/checkout@v4
        with:
          repository: gibbs-snyk/snyk-workflow-master
          path: 'snyk-workflow-master'  # This is where the repo is checked out

      - name: Upload snyk.yml file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-filter-master
          path: snyk-workflow-master/snyk-filter-master/snyk.yml

  test:
    needs: collect-snyk-filter-master  # Ensures this job waits for the previous one
    runs-on: ubuntu-latest
  
    steps:
      - name: Download snyk.yml file artifact
        uses: actions/download-artifact@v3
        with:
          name: snyk-filter-master

      - name: Display snyk.yml file contents
        run: cat ./snyk-filter-master/snyk.yml
