name: Call snyk-workflow-master

on: workflow_dispatch

 calling-workflow:
    uses: gibbs-snyk/snyk-workflow-master/.github/workflows/snyk-workflow-master.yml@main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
