name: Call snyk-workflow-master

on: workflow_dispatch

jobs:
  collect-snyk-filter-master:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout .snyk file from private repo
        uses: actions/checkout@v4
        with:
          repository: gibbs-snyk/snyk-workflow-master
          path: 'snyk-filter-master'

      - name: Upload .snyk file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-filter-master
          path: snyk-filter-master/.snyk

  test:
    needs: collect-snyk-filter-master  # Ensures this job waits for the previous one
    runs-on: ubuntu-latest
  
    steps:
      - name: Download .snyk file artifact
        uses: actions/download-artifact@v3
        with:
          name: snyk-filter-master
          path: .snyk-filter-master


      - name: Display .snyk file contents
        run: cat .snyk-filter-master/.snyk
